name: ItemEconomy
main: io.github.adrianvic.itemeconomy.Main
version: 1.1
depend:
- Vault
api-version: '1.21'
commands:
  itecoreload:
    description: Reloads the config for ItemEconomy
    usage: /itecoreload
    permission: iteco.reload